(define (problem problem6) 
(:domain Hamilton_cycle)
(:objects n1 n2 n3 n4 - noeud)

(:init
    (liaison n1 n2)
    (liaison n2 n1)
    (liaison n2 n3)
    (liaison n3 n2)
    (liaison n1 n3)
    (liaison n3 n1)
    (liaison n3 n4)
    (liaison n4 n3)
    (liaison n4 n1)
    (liaison n1 n4)
    (noeudNonVisite n1)
    (noeudNonVisite n2)
    (noeudNonVisite n3)
    (noeudNonVisite n4)
    (notInit)
)

(:goal (and
    (noeudVisite n1)
    (noeudVisite n2)
    (noeudVisite n3)
    (noeudVisite n4)
)
)
)
