(define (problem problem3)
(:domain n-puzzle)
(:objects a b c d e f g h - case e1 e2 e3 e4 e5 e6 e7 e8 e9 - emplacement cv - caseVide)

(:init  (limiteHaut e1)
        (limiteGauche e1)
        (limiteHaut e2)
        (limiteHaut e3)
        (limiteGauche e4)
        (limiteGauche e7)
        (limiteDroit e3)
        (limiteDroit e6)
        (limiteDroit e9)
        (limiteBas e7)
        (limiteBas e8)
        (limiteBas e9)
        (estSur a e1)
        (estSur b e2)
        (estSur c e4)
        (estSur d e3)
        (estSur e e5)
        (estSur f e6)
        (estSur g e7)
        (estSur h e8)
        (aVoisinBas e1 e4)
        (aVoisinBas e2 e5)
        (aVoisinBas e3 e6)
        (aVoisinBas e4 e7)
        (aVoisinBas e5 e8)
        (aVoisinBas e6 e9)
        (aVoisinDroit e1 e2)
        (aVoisinDroit e2 e3)
        (aVoisinDroit e4 e5)
        (aVoisinDroit e5 e6)
        (aVoisinDroit e7 e8)
        (aVoisinDroit e8 e9)
        (aVoisinHaut e4 e1)
        (aVoisinHaut e5 e2)
        (aVoisinHaut e6 e3)
        (aVoisinHaut e7 e4)
        (aVoisinHaut e8 e5)
        (aVoisinHaut e9 e6)
        (aVoisinGauche e2 e1)
        (aVoisinGauche e3 e2)
        (aVoisinGauche e5 e4)
        (aVoisinGauche e6 e5)
        (aVoisinGauche e8 e7)
        (aVoisinGauche e9 e8)
        (estCaseVideSur cv e9)
)

(:goal  (and (estCaseVideSur cv e9)
             (estSur a e1)
             (estSur b e2)
             (estSur c e3)
             (estSur d e4)
             (estSur e e5)
             (estSur f e6)
             (estSur g e7)
             (estSur h e8))
)
)