(define (problem problem4)
(:domain graph-color)
(:objects n1 n2 n3 n4 n5 n6 - noeud c1 c2 c3 - color)

(:init  (estNonColore n1)
        (estNonColore n2)
        (estNonColore n3)
        (estNonColore n4)
        (estNonColore n5)
        (estNonColore n6)
        (sontVoisins n1 n2) (sontVoisins n2 n1)
        (sontVoisins n2 n3) (sontVoisins n3 n2)
        (sontVoisins n2 n4) (sontVoisins n4 n2)
        (sontVoisins n6 n5) (sontVoisins n5 n6)
        (sontVoisins n2 n5) (sontVoisins n5 n2)
        (sontVoisins n4 n5) (sontVoisins n5 n4)
        (pasMarques n1 n2)  (pasMarques n2 n1)
        (pasMarques n2 n3)  (pasMarques n3 n2)
        (pasMarques n2 n4)  (pasMarques n4 n2)
        (pasMarques n6 n5)  (pasMarques n5 n6)
        (pasMarques n2 n5)  (pasMarques n5 n2)
        (pasMarques n4 n5)  (pasMarques n5 n4)
        (couleursDiff c1 c2)
        (couleursDiff c2 c3)
        (couleursDiff c3 c1)
)

(:goal  
        (and (sontMarques n1 n2)
             (sontMarques n2 n3)
             (sontMarques n2 n4)
             (sontMarques n6 n5)
             (sontMarques n2 n5)
             (sontMarques n4 n5)
        )
)
)