(define (problem problemSokoban)
(:domain sokoban)
(:objects a1 - agent
    e1 e2 e3 e4 e5 e6 e7 c1 - sol
    b1 - boite
)
(:init  (aVoisinDroit e1 e2)
        (aVoisinGauche e2 e1)
        (aVoisinDroit e3 e4)
        (aVoisinGauche e4 e3)
        (aVoisinDroit c1 e5)
        (aVoisinGauche e5 c1)
        (aVoisinHaut e7 e6)
        (aVoisinBas e6 e7)
        (aVoisinHaut e6 e5)
        (aVoisinBas e5 e6)
        (aVoisinHaut e5 e4)
        (aVoisinBas e4 e5)
        (aVoisinHaut c1 e3)
        (aVoisinBas e3 c1)
        (aVoisinHaut e4 e2)
        (aVoisinBas e2 e4)
        (aVoisinHaut e3 e1)
        (aVoisinBas e1 e3)
        (estDestination c1)
        (estSur a1 e7)
        (estSur b1 e3)
        (estLibre e1)
        (estLibre e2)
        (estLibre e4)
        (estLibre e5)
        (estLibre e6)
        (estLibre c1)
        (notCibleAtteinte c1)
        (notCibleAtteinte e1)
        (notCibleAtteinte e2)
        (notCibleAtteinte e3)
        (notCibleAtteinte e4)
        (notCibleAtteinte e5)
        (notCibleAtteinte e6)
        (notCibleAtteinte e7)

)

(:goal (and (cibleAtteinte c1))
)

)