(define (problem parsedProblem)
(:domain sokoban)
(:objects s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s12 s13 s14 s15 s16 s17 s18 s19 s20 c1 c2 c3 - sol
a1 - agent
b1 b2 b3 - boite)

(:init 
    (estLibre s12)
    (notCibleAtteinte s12)
    (estLibre s8)
    (notCibleAtteinte s8)
    (aVoisinDroit s12 s8)
    (aVoisinGauche s8 s12)
    (estLibre s15)
    (notCibleAtteinte s15)
    (aVoisinHaut s15 s12)
    (aVoisinBas s12 s15)
    (estLibre s6)
    (notCibleAtteinte s6)
    (aVoisinDroit s15 s6)
    (aVoisinGauche s6 s15)
    (aVoisinHaut s6 s8)
    (aVoisinBas s8 s6)
    (estLibre s11)
    (notCibleAtteinte s11)
    (estLibre s13)
    (notCibleAtteinte s13)
    (aVoisinDroit s11 s13)
    (aVoisinGauche s13 s11)
    (estLibre s4)
    (notCibleAtteinte s4)
    (aVoisinHaut s4 s11)
    (aVoisinBas s11 s4)
    (estDestination c2)
    (estLibre c2)
    (notCibleAtteinte c2)
    (aVoisinDroit s4 c2)
    (aVoisinGauche c2 s4)
    (aVoisinHaut c2 s13)
    (aVoisinBas s13 c2)
    (estLibre s5)
    (notCibleAtteinte s5)
    (estLibre s18)
    (notCibleAtteinte s18)
    (aVoisinDroit s5 s18)
    (aVoisinGauche s18 s5)
    (estSur b1 c1)
    (estDestination c1)
    (notCibleAtteinte c1)
    (aVoisinDroit s18 c1)
    (aVoisinGauche c1 s18)
    (aVoisinHaut c1 s4)
    (aVoisinBas s4 c1)
    (estLibre s9)
    (notCibleAtteinte s9)
    (aVoisinDroit c1 s9)
    (aVoisinGauche s9 c1)
    (aVoisinHaut s9 c2)
    (aVoisinBas c2 s9)
    (estLibre s2)
    (notCibleAtteinte s2)
    (aVoisinHaut s2 s5)
    (aVoisinBas s5 s2)
    (estSur a1 s19)
    (notCibleAtteinte s19)
    (aVoisinHaut s19 c1)
    (aVoisinBas c1 s19)
    (estLibre s3)
    (notCibleAtteinte s3)
    (aVoisinDroit s19 s3)
    (aVoisinGauche s3 s19)
    (aVoisinHaut s3 s9)
    (aVoisinBas s9 s3)
    (estLibre s10)
    (notCibleAtteinte s10)
    (aVoisinHaut s10 s2)
    (aVoisinBas s2 s10)
    (estSur b3 s16)
    (notCibleAtteinte s16)
    (aVoisinDroit s10 s16)
    (aVoisinGauche s16 s10)
    (estSur b2 c3)
    (estDestination c3)
    (notCibleAtteinte c3)
    (aVoisinDroit s16 c3)
    (aVoisinGauche c3 s16)
    (aVoisinHaut c3 s19)
    (aVoisinBas s19 c3)
    (estLibre s1)
    (notCibleAtteinte s1)
    (aVoisinDroit c3 s1)
    (aVoisinGauche s1 c3)
    (aVoisinHaut s1 s3)
    (aVoisinBas s3 s1)
    (estLibre s7)
    (notCibleAtteinte s7)
    (aVoisinHaut s7 s16)
    (aVoisinBas s16 s7)
    (estLibre s17)
    (notCibleAtteinte s17)
    (aVoisinDroit s7 s17)
    (aVoisinGauche s17 s7)
    (aVoisinHaut s17 c3)
    (aVoisinBas c3 s17)
    (estLibre s14)
    (notCibleAtteinte s14)
    (aVoisinDroit s17 s14)
    (aVoisinGauche s14 s17)
    (aVoisinHaut s14 s1)
    (aVoisinBas s1 s14)
    (estLibre s20)
    (notCibleAtteinte s20)
)
(:goal (and 
    (cibleAtteinte c2)
    (cibleAtteinte c1)
    (cibleAtteinte c3)
)
)
)